export const theme = {
  colors: {
    background: '#F4F8FF',
    backgroundAccent: '#EAF2FF',
    surface: '#FFFFFF',
    surfaceMuted: '#F8FBFF',
    primary: '#0B6EFD',
    primaryDark: '#084A9E',
    primaryMuted: '#7CAEF7',
    primarySoft: '#DDEBFF',
    success: '#1E8E5A',
    danger: '#C43D3D',
    border: '#D8E2F0',
    textPrimary: '#102033',
    textSecondary: '#3C516B',
    textMuted: '#71839A',
    white: '#FFFFFF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 20,
    xl: 28,
    xxl: 36,
    xxxl: 48,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 18,
  },
  typography: {
    sizes: {
      xs: 12,
      sm: 13,
      md: 16,
      lg: 20,
      xl: 24,
      display: 36,
      temperature: 64,
    },
    weights: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
  shadows: {
    card: {
      elevation: 4,
      shadowColor: '#102033',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 18,
    },
  },
};
